//AUTHENTICATION
export const POST_LOGIN_SAGA = 'POST_LOGIN_SAGA';

// export const FORGOT_PASSWORD_SAGA = 'FORGOT_PASSWORD_SAGA';
// export const RESET_PASSWORD_SAGA = 'RESET_PASSWORD_SAGA';

// // PRODUCTS
// export const GET_LIST_PRODUCTS_SAGA = 'GET_LIST_PRODUCTS_SAGA';
// export const POST_PRODUCTS_SAGA = 'POST_PRODUCTS_SAGA';
// export const PUT_PRODUCTS_SAGA = 'PUT_PRODUCTS_SAGA';
// export const DELETE_PRODUCTS_SAGA = 'DELETE_PRODUCTS_SAGA';
// export const GET_PRODUCTS_BY_ID_SAGA = 'GET_PRODUCTS_BY_ID_SAGA';

//CATEGORIES
export const GET_CATEGORIES_SAGA = 'GET_CATEGORIES_SAGA';

//STAFF
export const POST_STAFF_SAGA = 'POST_STAFF_SAGA';

//PRODUCTS
export const GET_PRODUCTS_SAGA = 'GET_PRODUCTS_SAGA';
export const GET_PRODUCT_BY_ID_SAGA = 'GET_PRODUCT_BY_ID_SAGA';
