// //AUTHENTICATION
// export const LOGIN_WITH_EMAIL_PASSWORD_SAGA = 'LOGIN_WITH_EMAIL_PASSWORD_SAGA';
// export const FORGOT_PASSWORD_SAGA = 'FORGOT_PASSWORD_SAGA';
// export const RESET_PASSWORD_SAGA = 'RESET_PASSWORD_SAGA';

// // PRODUCTS
// export const GET_LIST_PRODUCTS_SAGA = 'GET_LIST_PRODUCTS_SAGA';
// export const POST_PRODUCTS_SAGA = 'POST_PRODUCTS_SAGA';
// export const PUT_PRODUCTS_SAGA = 'PUT_PRODUCTS_SAGA';
// export const DELETE_PRODUCTS_SAGA = 'DELETE_PRODUCTS_SAGA';
// export const GET_PRODUCTS_BY_ID_SAGA = 'GET_PRODUCTS_BY_ID_SAGA';

// //DELIVERY NOTES
// export const GET_LIST_DELIVERY_NOTES_SAGA = 'GET_LIST_DELIVERY_NOTES_SAGA';
// export const POST_DELIVERY_NOTES_SAGA = 'POST_DELIVERY_NOTES_SAGA';
// export const DELETE_DELIVERY_NOTES_SAGA = 'DELETE_DELIVERY_NOTES_SAGA';
// export const GET_DELIVERY_NOTES_ID_SAGA = 'GET_DELIVERY_NOTES_ID_SAGA';

// //REPORT
// export const GET_REPORT_YEAR_SAGA = 'GET_REPORT_YEAR_SAGA';
// export const GET_REPORT_MONTH_SAGA = 'GET_REPORT_MONTH_SAGA';
// export const GET_REPORT_WEEK_SAGA = 'GET_REPORT_WEEK_SAGA';
// export const GET_REPORT_YEAR_EXCEL_SAGA = 'GET_REPORT_YEAR_EXCEL_SAGA';
// export const GET_REPORT_MONTH_EXCEL_SAGA = 'GET_REPORT_MONTH_EXCEL_SAGA';
// export const GET_REPORT_WEEK_EXCEL_SAGA = 'GET_REPORT_WEEK__EXCEL_SAGA';
