//AUTHENTICATION
export const GET_CURRENT_USER_SAGA = 'GET_CURRENT_USER_SAGA';
export const PUT_CURRENT_USER_SAGA = 'PUT_CURRENT_USER_SAGA';

// export const FORGOT_PASSWORD_SAGA = 'FORGOT_PASSWORD_SAGA';
// export const RESET_PASSWORD_SAGA = 'RESET_PASSWORD_SAGA';

// // PRODUCTS
// export const GET_LIST_PRODUCTS_SAGA = 'GET_LIST_PRODUCTS_SAGA';
// export const POST_PRODUCTS_SAGA = 'POST_PRODUCTS_SAGA';
// export const PUT_PRODUCTS_SAGA = 'PUT_PRODUCTS_SAGA';
// export const DELETE_PRODUCTS_SAGA = 'DELETE_PRODUCTS_SAGA';
// export const GET_PRODUCTS_BY_ID_SAGA = 'GET_PRODUCTS_BY_ID_SAGA';

//CATEGORIES
export const GET_CATEGORIES_SAGA = 'GET_CATEGORIES_SAGA';
export const UPDATE_CATEGORY_SAGA = 'UPDATE_CATEGORY_SAGA';
export const REMOVE_CATEGORY_SAGA = 'REMOVE_CATEGORY_SAGA';
export const CREATE_CATEGORY_SAGA = 'CREATE_CATEGORY_SAGA';

//STAFF
export const POST_STAFF_SAGA = 'POST_STAFF_SAGA';
export const GET_STAFFS_SAGA = 'GET_STAFFS_SAGA';
export const DELETE_STAFF_SAGA = 'DELETE_STAFFS_SAGA';
export const GET_STAFF_BY_ID_SAGA = 'GET_STAFF_BY_ID_SAGA';
export const PUT_STAFF_SAGA = 'PUT_STAFF_SAGA';

//PRODUCTS
export const GET_PRODUCTS_SAGA = 'GET_PRODUCTS_SAGA';
export const GET_PRODUCT_BY_ID_SAGA = 'GET_PRODUCT_BY_ID_SAGA';

//CUSTOMER
export const GET_CUSTOMERS_SAGA = 'GET_CUSTOMERS_SAGA';
export const GET_CUSTOMER_BY_ID_SAGA = 'GET_CUSTOMER_BY_ID_SAGA';
