//AUTHENTICATION
export const GET_CURRENT_USER_SAGA = 'GET_CURRENT_USER_SAGA';
export const PUT_CURRENT_USER_SAGA = 'PUT_CURRENT_USER_SAGA';

//CATEGORIES
export const GET_CATEGORIES_SAGA = 'GET_CATEGORIES_SAGA';
export const UPDATE_CATEGORY_SAGA = 'UPDATE_CATEGORY_SAGA';
export const REMOVE_CATEGORY_SAGA = 'REMOVE_CATEGORY_SAGA';
export const CREATE_CATEGORY_SAGA = 'CREATE_CATEGORY_SAGA';

//STAFF
export const POST_STAFF_SAGA = 'POST_STAFF_SAGA';
export const GET_STAFFS_SAGA = 'GET_STAFFS_SAGA';
export const DELETE_STAFF_SAGA = 'DELETE_STAFFS_SAGA';
export const GET_STAFF_BY_ID_SAGA = 'GET_STAFF_BY_ID_SAGA';
export const PUT_STAFF_SAGA = 'PUT_STAFF_SAGA';

//PRODUCTS
export const GET_PRODUCTS_SAGA = 'GET_PRODUCTS_SAGA';
export const GET_PRODUCT_BY_ID_SAGA = 'GET_PRODUCT_BY_ID_SAGA';
export const CREATE_PRODUCT_SAGA = 'CREATE_PRODUCT_SAGA';
export const UPDATE_PRODUCT_SAGA = 'UPDATE_PRODUCT_SAGA';
export const STOP_SELLING_PRODUCT_SAGA = 'STOP_SELLING_PRODUCT_SAGA';
export const RESELL_PRODUCT_SAGA = 'RESELL_PRODUCT_SAGA';

//CUSTOMER
export const GET_CUSTOMERS_SAGA = 'GET_CUSTOMERS_SAGA';
export const GET_CUSTOMER_BY_ID_SAGA = 'GET_CUSTOMER_BY_ID_SAGA';

// RECEIPTS
export const GET_RECEIPTS_SAGA = 'GET_RECEIPTS_SAGA';
export const CREATE_RECEIPT_SAGA = 'CREATE_RECEIPT_SAGA';
export const GET_RECEIPT_BY_ID_SAGA = 'GET_RECEIPT_BY_ID_SAGA';
export const UPDATE_RECEIPT_SAGA = 'UPDATE_RECEIPT_SAGA';

//ORDER
export const GET_ORDERS_SAGA = 'GET_ORDERS_SAGA';
export const GET_ORDER_BY_ID_SAGA = 'GET_ORDER_BY_ID_SAGA';

// DASHBOARD
export const GET_STAT_CARD_DATA = 'GET_STAT_CARD_DATA';
export const GET_REVENUE = 'GET_REVENUE';
export const GET_BEST_SELLER_PRODUCTS = 'GET_BEST_SELLER_PRODUCTS';
